# Generated by Django 5.1.5 on 2025-10-26 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_hermine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HermineUserMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sent', models.DateTimeField(null=True)),
            ],
        ),
    ]
