# Generated by Django 6.0 on 2025-12-21 19:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_hermine', '0002_hermineusermessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='herminechannelmessage',
            name='delay',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='herminechannelmessage',
            name='error',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hermineusermessage',
            name='delay',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hermineusermessage',
            name='error',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
