# Generated by Django 6.0 on 2025-12-21 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_hermine', '0003_herminechannelmessage_delay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herminechannelmessage',
            name='error',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='hermineusermessage',
            name='error',
            field=models.TextField(blank=True),
        ),
    ]
