# Generated by Django 5.1.5 on 2025-11-10 22:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funktion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funktion_label', models.CharField(blank=True, help_text='Optionale Funktionsbezeichnung wie in THWin (z.B. Gruppenführer/in Elektroversorgung).', max_length=40, verbose_name='Funktion')),
            ],
            options={
                'verbose_name': 'Funktion',
                'verbose_name_plural': 'Funktionen',
                'ordering': ('funktion_label',),
            },
        ),
        migrations.CreateModel(
            name='Termin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repeat_uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID zur Identifikation von Terminwiederholungen.', verbose_name='Serien-UUID')),
                ('label', models.CharField(help_text='Terminbeschreibung, z.B. "Bergung Theorie Gesteinsbearbeitung".', max_length=150, verbose_name='Bezeichner')),
                ('description', models.TextField(blank=True, help_text='Eigene Notizen zum Termin.', verbose_name='Beschreibung')),
                ('start', models.DateTimeField(help_text='Beginn des Termins, sollte im Regelfall in der Zukunft liegen.', verbose_name='Start')),
                ('end', models.DateTimeField(help_text='Ende des Termins, muss nach dem Beginn des Termins liegen.', verbose_name='Ende')),
            ],
            options={
                'verbose_name': 'Termin',
                'verbose_name_plural': 'Termine',
                'ordering': ('start', 'label'),
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selectable', models.BooleanField(default=True, help_text='Ressourcen die nicht auswählbar sind, stehen nicht direkt für Termine zur Verfügung, sondern dienen der Strukturierung von untergeordneten Ressourcen.', verbose_name='Auswählbar?')),
                ('label', models.CharField(help_text='Eindeutige Bezeichnung der Ressource, die auch ohne den Kontext der übergeordneten Ressource verständlich ist.', max_length=70, unique=True, verbose_name='Bezeichner')),
                ('slug', models.SlugField(help_text='Kurzbezeichner der in URLs verwendet werden kann. Sollte nicht geändert werden, um ggf. bestehende URLs nicht zu beschädigen.', unique=True, verbose_name='URL-Bezeichner')),
                ('part_of', models.ForeignKey(blank=True, help_text='Ressource von der diese Ressource ein Teil ist. Wird eine übergeordnete Ressource gebucht, werden die Verwalter dieser Ressource lediglich informiert.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consists_of', to='reservierung.resource', verbose_name='Übergeordnete Ressource')),
            ],
            options={
                'verbose_name': 'Ressource',
                'verbose_name_plural': 'Ressourcen',
                'ordering': ('label',),
            },
        ),
        migrations.CreateModel(
            name='ResourceManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voting_group', models.CharField(blank=True, help_text='Je Ressource können mehrere Abstimmungsgruppen gebildet werden: Aus jeder Abstimmungsgruppe muss dann mindestens eine Person der Buchung zustimmen. Eine leere Abstimmungsgruppe wird für Personen verwendet, die nicht abstimmen müssen, aber über erfolgreiche Buchungen informiert werden sollen.', max_length=15, verbose_name='Abstimmungsgruppe')),
                ('admin', models.BooleanField(help_text='Erlaube diesen Benutzern Belegungen (auch für untergeordnete Ressourcen) zu stornieren.', verbose_name='Administrator')),
                ('funktion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='reservierung.funktion')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='reservierung.resource')),
            ],
            options={
                'verbose_name': 'Ressourcenverwalter',
                'verbose_name_plural': 'Ressourcenverwalter',
                'ordering': ('resource', 'voting_group', 'funktion'),
            },
        ),
        migrations.CreateModel(
            name='ResourceUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='reservierung.resource')),
                ('termin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='reservierung.termin')),
            ],
            options={
                'verbose_name': 'Buchung',
                'verbose_name_plural': 'Buchungen',
                'ordering': ('termin', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, help_text='Benutzername in NextCloud zur Anmeldung.', max_length=50, verbose_name='Benutzername')),
                ('firstname', models.CharField(blank=True, help_text='Vorname wie in THWin', max_length=40, verbose_name='Vorname')),
                ('surname', models.CharField(blank=True, help_text='Nachname wie in THWin', max_length=40, verbose_name='Nachname')),
            ],
            options={
                'verbose_name': 'Benutzer',
                'verbose_name_plural': 'Benutzer',
                'ordering': ('surname', 'firstname', 'username'),
                'indexes': [models.Index(fields=['username'], name='reservierun_usernam_516fb8_idx'), models.Index(fields=['firstname', 'surname'], name='reservierun_firstna_0ce406_idx')],
                'constraints': [models.UniqueConstraint(models.F('username'), models.F('firstname'), models.F('surname'), name='unique_user')],
            },
        ),
        migrations.AddField(
            model_name='termin',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Ersteller des Termins, kann ohne Wert sein, wenn der ursprüngliche Eigentümer gelöscht wurde.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='termine', to='reservierung.user', verbose_name='Eigentümer'),
        ),
        migrations.CreateModel(
            name='ResourceUsageLogMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('kind', models.CharField(blank=True, choices=[('meta', 'Anforderung erstellt oder geändert'), ('votes', 'Zustimmungen'), ('rejects', 'Ablehnungen'), ('state', 'Statusänderungen'), ('user', 'Benutzerkommentare')], max_length=20)),
                ('message', models.TextField()),
                ('usage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_messages', to='reservierung.resourceusage')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_messages', to='reservierung.user')),
            ],
            options={
                'verbose_name': 'Lognachricht',
                'verbose_name_plural': 'Lognachrichten',
                'ordering': ('timestamp',),
            },
        ),
        migrations.CreateModel(
            name='ResourceUsageConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, help_text='Freitext durch den Genehmiger an Anfragenden zur Klarstellung von Details.', verbose_name='Verwendungshinweis')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Genehmigungsdatum')),
                ('revoked_at', models.DateTimeField(blank=True, help_text='Datum zu dem die Genehmigung zurückgezogen wurde (leer wenn die Genehmigung gültig ist)', null=True, verbose_name='Zurückgezogen')),
                ('revoke_reason', models.CharField(blank=True, choices=[('termin_change', 'Änderung an Termin'), ('approver', 'Durch Genehmiger zurückgezogen')], help_text='Grund für den Rückzug der Genehmigung.', max_length=20, verbose_name='Rückzugsgrund')),
                ('resource_usage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='reservierung.resourceusage', verbose_name='Verwendung')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='reservierung.user', verbose_name='Genehmiger')),
            ],
            options={
                'verbose_name': 'Buchungsbestätigung',
                'verbose_name_plural': 'Buchungsbestätigungen',
                'ordering': ('resource_usage', 'created_at'),
            },
        ),
        migrations.AddField(
            model_name='resourceusage',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usages_rejected', to='reservierung.user'),
        ),
        migrations.AddField(
            model_name='funktion',
            name='user',
            field=models.ManyToManyField(related_name='funktionen', to='reservierung.user'),
        ),
        migrations.AddIndex(
            model_name='termin',
            index=models.Index(fields=['start', 'end'], name='reservierun_start_eddabf_idx'),
        ),
        migrations.AddIndex(
            model_name='resourceusageconfirmation',
            index=models.Index(fields=['resource_usage', 'approver'], name='reservierun_resourc_073106_idx'),
        ),
        migrations.AddIndex(
            model_name='resourceusage',
            index=models.Index(fields=['termin', 'resource'], name='reservierun_termin__71dac6_idx'),
        ),
        migrations.AddConstraint(
            model_name='resourceusage',
            constraint=models.UniqueConstraint(fields=('termin', 'resource'), name='termin_resource'),
        ),
        migrations.AddIndex(
            model_name='funktion',
            index=models.Index(fields=['funktion_label'], name='reservierun_funktio_8338ac_idx'),
        ),
    ]
