# Generated by Django 5.1.5 on 2025-11-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservierung', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funktion',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='funktionen', to='reservierung.user'),
        ),
    ]
