# Generated by Django 5.2.7 on 2025-12-15 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservierung', '0002_alter_funktion_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourceusageconfirmation',
            name='revoke_reason',
        ),
    ]
