# Generated by Django 5.2.7 on 2025-12-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservierung', '0003_remove_resourceusageconfirmation_revoke_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funktion',
            name='funktion_label',
            field=models.CharField(blank=True, help_text='Optionale Funktionsbezeichnung wie in THWin (z.B. Gruppenführer/in Elektroversorgung).', max_length=50, verbose_name='Funktion'),
        ),
    ]
