# Generated by Django 5.0.4 on 2024-11-22 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.IntegerField(help_text='Sortierreihenfolge der Seite innerhalb der Unterweisung')),
                ('titel', models.CharField(help_text='Überschrift der Seite', max_length=50)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['unterweisung', 'sort'],
            },
        ),
        migrations.CreateModel(
            name='MultipleChoiceFrage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Überschrift der einzelnen Optionen', verbose_name='Fragetext')),
                ('sort', models.IntegerField(help_text='Sortierreihenfolge der Frage innerhalb der Seite', verbose_name='Sortierreihenfolge')),
                ('optional', models.BooleanField(default=False, verbose_name='Optionale Frage')),
            ],
            options={
                'verbose_name': 'Multiple-Choice Frage',
                'verbose_name_plural': 'Multiple-Choice Fragen',
                'ordering': ['seite', 'sort'],
            },
        ),
        migrations.CreateModel(
            name='Unterweisung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Eindeutiger Name der Unterweisung, z.B. "Kraftfahrerunterweisung 2024"', max_length=100, verbose_name='Bezeichnung')),
                ('short_label', models.CharField(help_text='Bezeichnung in Tabellenüberschriften, z.B. "Kf"', max_length=20, verbose_name='Kurzbezeichnung')),
                ('active', models.BooleanField(help_text='Soll die Unterweisung aktuell angezeigt werden?', verbose_name='Aktiv?')),
            ],
            options={
                'verbose_name': 'Unterweisung',
                'verbose_name_plural': 'Unterweisungen',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='FuehrerscheinDatenSeite',
            fields=[
                ('seite_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='unterweisung.seite')),
            ],
            options={
                'verbose_name': 'Führerscheindaten-Eingabemaske',
                'verbose_name_plural': 'Führerscheindaten-Eingabemasken',
            },
            bases=('unterweisung.seite',),
        ),
        migrations.CreateModel(
            name='InfoSeite',
            fields=[
                ('seite_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='unterweisung.seite')),
                ('text', models.TextField(help_text='Unterstützt Markdown-Formatierung.', verbose_name='Erklärungstext')),
                ('media_position', models.CharField(choices=[('above', 'Über Text'), ('below', 'Unter Text'), ('left', 'Links neben Text'), ('right', 'Rechts neben Text')], help_text='Position des Erklärungsbildes relativ zum Erklärungstext.', max_length=10, verbose_name='Positionierung des Erklärungsbildes')),
                ('media', models.ImageField(blank=True, help_text='Kann frei bleiben, wenn kein Bild angezeigt werden soll.', null=True, upload_to='infoseiten/', verbose_name='Erklärungsbild')),
            ],
            options={
                'verbose_name': 'Folie',
                'verbose_name_plural': 'Folien',
            },
            bases=('unterweisung.seite',),
        ),
        migrations.CreateModel(
            name='MultipleChoiceSeite',
            fields=[
                ('seite_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='unterweisung.seite')),
                ('min_richtig', models.IntegerField(default=0, help_text='Wie viele Fragen muss ein*e Teilnehmer*in richtig beantworten, um die Seite zu bestehen. Hinweis: Erforderliche Fragen müssen immer richtig beantwortet werden.', verbose_name='Benötigte richtig beantwortete Fragen')),
            ],
            options={
                'verbose_name': 'Multiple-Choice Seite',
                'verbose_name_plural': 'Multiple-Choice Seiten',
            },
            bases=('unterweisung.seite',),
        ),
        migrations.CreateModel(
            name='MultipleChoiceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('richtig', models.BooleanField(help_text='Hinweis: Wird genau eine Antwort der Frage als richtig ausgewählt, werden diese als Auswahlbox angezeigt, anderenfalls wird eine Mehrfachauswahl angeboten.', verbose_name='Richtige Antwort?')),
                ('text', models.TextField(help_text='Antwortmöglichkeit zur Frage, welche in zufälliger Reihenfolge angezeigt werden', verbose_name='Antworttext')),
                ('frage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unterweisung.multiplechoicefrage')),
            ],
            options={
                'verbose_name': 'Multiple-Choice Antwort',
                'verbose_name_plural': 'Multiple-Choice Antworten',
            },
        ),
        migrations.CreateModel(
            name='Teilnahme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('fullname', models.CharField(max_length=70)),
                ('abgeschlossen_at', models.DateTimeField(blank=True, null=True)),
                ('ergebnis', models.TextField()),
                ('unterweisung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teilnahmen', to='unterweisung.unterweisung')),
            ],
            options={
                'verbose_name': 'Teilnahme',
                'verbose_name_plural': 'Teilnahmen',
                'ordering': ['unterweisung', 'username'],
            },
        ),
        migrations.AddField(
            model_name='seite',
            name='unterweisung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seiten', to='unterweisung.unterweisung'),
        ),
        migrations.AddField(
            model_name='multiplechoicefrage',
            name='seite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fragen', to='unterweisung.multiplechoiceseite'),
        ),
    ]
