# Generated by Django 5.0.4 on 2024-11-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unterweisung', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unterweisung',
            name='description',
            field=models.TextField(default='', help_text='Beschreibung der Unterweisung, z.B. an welche Zielgruppe diese sich richtet.', verbose_name='Beschreibung'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unterweisung',
            name='success_text',
            field=models.TextField(default='', help_text='Text der nach Abschluss der Unterweisung angezeigt wird, z.B. um PIN-Codes bekannt zu geben.', verbose_name='Abschluss-Informationen'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='infoseite',
            name='media_position',
            field=models.CharField(blank=True, choices=[('above', 'Über Text'), ('below', 'Unter Text'), ('left', 'Links neben Text'), ('right', 'Rechts neben Text')], help_text='Position des Erklärungsbildes relativ zum Erklärungstext.', max_length=10, verbose_name='Positionierung des Erklärungsbildes'),
        ),
        migrations.AlterField(
            model_name='teilnahme',
            name='ergebnis',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='teilnahme',
            name='fullname',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddConstraint(
            model_name='teilnahme',
            constraint=models.UniqueConstraint(fields=('username', 'unterweisung'), name='teilnahme_unique'),
        ),
    ]
