# Generated by Django 5.0.4 on 2024-11-23 13:41

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unterweisung', '0002_unterweisung_description_unterweisung_success_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infoseite',
            name='media',
        ),
        migrations.RemoveField(
            model_name='infoseite',
            name='media_position',
        ),
        migrations.RemoveField(
            model_name='infoseite',
            name='text',
        ),
        migrations.AddField(
            model_name='infoseite',
            name='content',
            field=markdownx.models.MarkdownxField(default=''),
            preserve_default=False,
        ),
    ]
