# Generated by Django 5.0.4 on 2024-11-23 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unterweisung', '0003_remove_infoseite_media_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplechoicefrage',
            name='optional',
            field=models.BooleanField(default=False, help_text='Eine optionale Frage muss nicht zwingend richtig beantwortet werden, um den Fragenkatalog einer Seite abzuschließen. Allerdings müssen je Seite mindestens eine einstellbare Zahl von Fragen richtig beantwortet werden, zu denen auch die optionalen Fragen zählen.', verbose_name='Optionale Frage'),
        ),
        migrations.AlterField(
            model_name='multiplechoiceoption',
            name='frage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antworten', to='unterweisung.multiplechoicefrage'),
        ),
    ]
