# Generated by Django 5.0.4 on 2024-11-23 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unterweisung', '0004_alter_multiplechoicefrage_optional_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='multiplechoicefrage',
            options={'ordering': ['sort'], 'verbose_name': 'Multiple-Choice Frage', 'verbose_name_plural': 'Multiple-Choice Fragen'},
        ),
        migrations.AlterModelOptions(
            name='seite',
            options={'ordering': ['unterweisung', 'sort'], 'verbose_name': 'Seite', 'verbose_name_plural': 'Seiten'},
        ),
        migrations.RemoveField(
            model_name='multiplechoicefrage',
            name='seite',
        ),
        migrations.AddField(
            model_name='multiplechoiceseite',
            name='fragen',
            field=models.ManyToManyField(related_name='seiten', to='unterweisung.multiplechoicefrage'),
        ),
    ]
