# Generated by Django 5.0.4 on 2024-11-23 16:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unterweisung', '0005_alter_multiplechoicefrage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplechoiceseite',
            name='min_richtig',
            field=models.IntegerField(default=0, help_text='Wie viele Fragen muss ein*e Teilnehmer*in richtig beantworten, um die Seite zu bestehen. Hinweis: Erforderliche Fragen müssen immer richtig beantwortet werden.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Benötigte richtig beantwortete Fragen'),
        ),
    ]
