# Generated by Django 5.1.3 on 2024-11-24 13:11

import unterweisung.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unterweisung', '0006_alter_multiplechoiceseite_min_richtig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seite',
            name='unterweisung',
            field=models.ForeignKey(on_delete=unterweisung.models.NON_POLYMORPHIC_CASCADE, related_name='seiten', to='unterweisung.unterweisung'),
        ),
        migrations.AlterField(
            model_name='unterweisung',
            name='label',
            field=models.CharField(help_text='Eindeutiger Name der Unterweisung, z.B. "Kraftfahrerunterweisung 2024"', max_length=100, unique=True, verbose_name='Bezeichnung'),
        ),
    ]
