# Generated by Django 5.1.3 on 2024-11-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unterweisung', '0007_alter_seite_unterweisung_alter_unterweisung_label'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seite',
            options={'ordering': ['sort'], 'verbose_name': 'Seite', 'verbose_name_plural': 'Seiten'},
        ),
        migrations.AlterField(
            model_name='multiplechoicefrage',
            name='sort',
            field=models.IntegerField(db_index=True, default=0, help_text='Sortierreihenfolge der Frage innerhalb der Seite', verbose_name='Sortierreihenfolge'),
        ),
        migrations.AlterField(
            model_name='seite',
            name='sort',
            field=models.IntegerField(db_index=True, default=0, help_text='Sortierreihenfolge der Seite innerhalb der Unterweisung'),
        ),
    ]
