# Generated by Django 5.1.3 on 2024-11-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unterweisung', '0008_alter_seite_options_alter_multiplechoicefrage_sort_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seite',
            name='titel',
            field=models.CharField(help_text='Überschrift der Seite', max_length=70),
        ),
    ]
