# Generated by Django 5.1.3 on 2024-12-01 20:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unterweisung', '0009_alter_seite_titel'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoseite',
            name='min_time',
            field=models.IntegerField(default=10, help_text='Wie lange (in Sekunden) muss diese Seite mindestens angezeigt werden, um als bestanden zu zählen?', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Mindestaufenthalt'),
        ),
    ]
