# Generated by Django 5.1.3 on 2024-12-22 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unterweisung', '0010_infoseite_min_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='HermineNachrichtSeite',
            fields=[
                ('seite_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='unterweisung.seite')),
                ('ziel_gruppe', models.CharField(help_text='Gruppe, in der die Nachricht geschrieben werden soll. In dieser muss der Bot Schreibrechte haben.', max_length=20, verbose_name='Hermine-Gruppe')),
                ('description', models.TextField(help_text='Informationstext für den Benutzer', verbose_name='Beschreibung')),
                ('anonymous', models.BooleanField(help_text='Soll die Hermine-Nachricht anonym erfolgen oder den Namen des aktuellen Benutzers enthalten?', verbose_name='Anonym?')),
                ('required', models.BooleanField(help_text='Muss eine Nachricht angegeben werden oder kann dies unterbleiben?', verbose_name='Erforderlich?')),
                ('force_message', models.BooleanField(help_text='Soll auch eine (leere) Nachricht gesendet werden wenn der Benutzer keine angegeben hat?', verbose_name='Erzwinge eine Nachricht?')),
            ],
            options={
                'verbose_name': 'Nachrichten-Seite',
                'verbose_name_plural': 'Nachrichten-Seiten',
            },
            bases=('unterweisung.seite',),
        ),
    ]
