# Generated by Django 5.1.3 on 2024-12-22 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unterweisung', '0011_herminenachrichtseite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herminenachrichtseite',
            name='ziel_gruppe',
            field=models.CharField(help_text='Gruppe, in der die Nachricht geschrieben werden soll. In dieser muss der Bot Schreibrechte haben.', max_length=50, verbose_name='Hermine-Gruppe'),
        ),
    ]
