# Generated by Django 5.1.3 on 2024-12-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unterweisung', '0012_alter_herminenachrichtseite_ziel_gruppe'),
    ]

    operations = [
        migrations.AddField(
            model_name='teilnahme',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
