# Generated by Django 5.1.3 on 2024-12-31 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unterweisung', '0013_teilnahme_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='seite',
            name='is_required',
            field=models.BooleanField(default=True, help_text='Muss diese Seite erfolgreich abgeschlossen werden, um eine Teilnahme zu hinterlegen?'),
        ),
    ]
