# Generated by Django 5.1.3 on 2025-01-09 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unterweisung', '0014_seite_is_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teilnehmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('fullname', models.CharField(blank=True, max_length=70)),
                ('gruppe', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='teilnahme',
            name='teilnehmer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teilnahmen', to='unterweisung.teilnehmer'),
        ),
    ]
