# Generated by Django 5.1.3 on 2025-01-09 17:22

from django.db import migrations


def fill_teilnehmer(apps, schema_editor):
    Teilnehmer = apps.get_model("unterweisung", "Teilnehmer")
    Teilnahme = apps.get_model("unterweisung", "Teilnahme")

    _teilnehmer = {}

    for teilnahme in Teilnahme.objects.all():
        if teilnahme.username not in _teilnehmer:
            _teilnehmer[teilnahme.username], _ = Teilnehmer.objects.get_or_create(
                username=teilnahme.username)

        if not _teilnehmer[teilnahme.username].fullname and teilnahme.fullname:
            _teilnehmer[teilnahme.username].fullname = teilnahme.fullname
            _teilnehmer[teilnahme.username].save()

        teilnahme.teilnehmer = _teilnehmer[teilnahme.username]
        teilnahme.save()


def fill_teilnahmen(apps, schema_editor):
    Teilnehmer = apps.get_model("unterweisung", "Teilnehmer")
    Teilnahme = apps.get_model("unterweisung", "Teilnahme")

    _teilnehmer = {}

    for teilnahme in Teilnahme.objects.all():
        teilnahme.username = teilnahme.teilnehmer.username
        teilnahme.fullname = teilnahme.teilnehmer.fullname
        teilnahme.save()


class Migration(migrations.Migration):

    dependencies = [
        ('unterweisung', '0015_teilnehmer_teilnahme_teilnehmer'),
    ]

    operations = [
        migrations.RunPython(code=fill_teilnehmer,
                             reverse_code=fill_teilnahmen)
    ]
