# Generated by Django 5.1.3 on 2025-01-09 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unterweisung', '0016_auto_20250109_1822'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teilnahme',
            options={'ordering': ['unterweisung', 'teilnehmer'], 'verbose_name': 'Teilnahme', 'verbose_name_plural': 'Teilnahmen'},
        ),
        migrations.AlterModelOptions(
            name='teilnehmer',
            options={'ordering': ['fullname', 'username'], 'verbose_name': 'Teilnehmer'},
        ),
        migrations.RemoveConstraint(
            model_name='teilnahme',
            name='teilnahme_unique',
        ),
        migrations.RemoveField(
            model_name='teilnahme',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='teilnahme',
            name='username',
        ),
        migrations.AlterField(
            model_name='teilnahme',
            name='teilnehmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teilnahmen', to='unterweisung.teilnehmer'),
        ),
        migrations.AlterField(
            model_name='teilnehmer',
            name='fullname',
            field=models.CharField(blank=True, max_length=70, verbose_name='Bürgerliche Name wie in THWin'),
        ),
        migrations.AlterField(
            model_name='teilnehmer',
            name='gruppe',
            field=models.CharField(blank=True, max_length=20, verbose_name='Gruppenkürzel zur Gruppierung von Teilnehmern'),
        ),
        migrations.AlterField(
            model_name='teilnehmer',
            name='username',
            field=models.CharField(max_length=50, unique=True, verbose_name='Benutzername in NextCloud'),
        ),
    ]
