# Generated by Django 5.1.3 on 2025-01-09 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unterweisung', '0017_alter_teilnahme_options_alter_teilnehmer_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teilnehmer',
            options={'ordering': ['fullname', 'username'], 'verbose_name': 'Teilnehmer', 'verbose_name_plural': 'Teilnehmer'},
        ),
    ]
