# Generated by Django 5.1.3 on 2025-01-10 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unterweisung', '0018_alter_teilnehmer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teilnehmer',
            options={'ordering': ['surname', 'firstname', 'username'], 'verbose_name': 'Teilnehmer', 'verbose_name_plural': 'Teilnehmer'},
        ),
        migrations.AddField(
            model_name='teilnehmer',
            name='firstname',
            field=models.CharField(blank=True, max_length=40, verbose_name='Vorname wie in THWin'),
        ),
        migrations.AddField(
            model_name='teilnehmer',
            name='surname',
            field=models.CharField(blank=True, max_length=40, verbose_name='Nachname wie in THWin'),
        ),
    ]
