# Generated by Django 5.1.3 on 2025-01-10 02:37

from django.db import migrations


def fill_surname(apps, schema_editor):
    Teilnehmer = apps.get_model("unterweisung", "Teilnehmer")

    for teilnehmer in Teilnehmer.objects.all():
        firstname, _, surname = teilnehmer.fullname.rpartition(" ")
        teilnehmer.firstname = firstname
        teilnehmer.surname = surname.replace("_", " ")
        teilnehmer.save()


def fill_fullname(apps, schema_editor):
    Teilnehmer = apps.get_model("unterweisung", "Teilnehmer")

    for teilnehmer in Teilnehmer.objects.all():
        teilnehmer.fullname = f"{teilnehmer.firstname} {teilnehmer.surname.replace(' ', '_')}"
        teilnehmer.save()


class Migration(migrations.Migration):

    dependencies = [
        ('unterweisung', '0019_alter_teilnehmer_options_teilnehmer_firstname_and_more'),
    ]

    operations = [
        migrations.RunPython(code=fill_surname, reverse_code=fill_fullname),
    ]
