# Generated by Django 5.1.3 on 2025-01-10 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unterweisung', '0020_auto_20250110_0337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teilnehmer',
            name='fullname',
        ),
    ]
