# Generated by Django 5.1.3 on 2025-01-12 23:32

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unterweisung', '0021_remove_teilnehmer_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplechoicefrage',
            name='text',
            field=markdownx.models.MarkdownxField(help_text='Überschrift der einzelnen Optionen', verbose_name='Fragetext'),
        ),
        migrations.AlterField(
            model_name='multiplechoiceoption',
            name='text',
            field=markdownx.models.MarkdownxField(help_text='Antwortmöglichkeit zur Frage, welche in zufälliger Reihenfolge angezeigt werden', verbose_name='Antworttext'),
        ),
    ]
