# Generated by Django 5.1.5 on 2025-01-29 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unterweisung', '0022_alter_multiplechoicefrage_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fuehrerschein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nummer', models.CharField(max_length=11)),
                ('teilnehmer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fuehrerschein', to='unterweisung.teilnehmer')),
            ],
            options={
                'verbose_name': 'Führerscheindaten',
                'verbose_name_plural': 'Führerscheindaten',
                'ordering': ['teilnehmer'],
            },
        ),
        migrations.CreateModel(
            name='Fahrerlaubnis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('klasse', models.CharField(choices=[('B', 'B'), ('BE', 'BE'), ('C1E', 'C1E'), ('C', 'C'), ('CE', 'CE')], max_length=3)),
                ('gueltig_ab', models.DateField()),
                ('gueltig_bis', models.DateField(blank=True, null=True)),
                ('fuehrerschein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fahrerlaubnisse', to='unterweisung.fuehrerschein')),
            ],
            options={
                'verbose_name': 'Fahrerlaubnis',
                'verbose_name_plural': 'Fahrerlaubnis',
                'ordering': ['fuehrerschein', 'klasse'],
                'constraints': [models.UniqueConstraint(models.F('fuehrerschein'), models.F('klasse'), name='unique_fuehrerschein_klasse')],
            },
        ),
    ]
