# Generated by Django 5.1.5 on 2025-01-29 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unterweisung', '0023_fuehrerschein_fahrerlaubnis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fahrerlaubnis',
            name='fuehrerschein',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fahrerlaubnisse', to='unterweisung.fuehrerschein', verbose_name='Führerschein'),
        ),
        migrations.AlterField(
            model_name='fahrerlaubnis',
            name='gueltig_ab',
            field=models.DateField(help_text='Datum zu der die Fahrerlaubnis erteilt wurde (üblicherweise Datum der Prüfung, notiert in Ziffer 10)', verbose_name='Erteilungsdatum'),
        ),
        migrations.AlterField(
            model_name='fahrerlaubnis',
            name='gueltig_bis',
            field=models.DateField(blank=True, help_text='Datum bis zu dem die Fahrerlaubnis befristet ist (sofern die Fahrerlaubnis befristet erteilt wurde). Notiert in Ziffer 11.', null=True, verbose_name='Gültigkeitsdatum'),
        ),
        migrations.AlterField(
            model_name='fahrerlaubnis',
            name='klasse',
            field=models.CharField(choices=[('B', 'B'), ('C', 'C'), ('BE', 'BE'), ('C1E', 'C1E'), ('CE', 'CE')], max_length=3, verbose_name='Fahrerlaubnisklasse'),
        ),
        migrations.AlterField(
            model_name='fuehrerschein',
            name='nummer',
            field=models.CharField(help_text='Nummer des Führerscheins (Ziffer 5)', max_length=11, verbose_name='Führerscheinnummer'),
        ),
        migrations.AlterField(
            model_name='fuehrerschein',
            name='teilnehmer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fuehrerschein', to='unterweisung.teilnehmer', verbose_name='Teilnehmer'),
        ),
    ]
