# Generated by Django 5.1.5 on 2025-11-27 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unterweisung', '0024_alter_fahrerlaubnis_fuehrerschein_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplechoicefrage',
            name='seite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fragen_neu', to='unterweisung.multiplechoiceseite'),
        ),
    ]
