# Generated by Django 5.1.5 on 2025-11-27 08:36

import django.db.models.deletion
from django.db import migrations, models


def fill_new(apps, schema_editor):
    MultipleChoiceSeite = apps.get_model("unterweisung", "MultipleChoiceSeite")
    MultipleChoiceFrage = apps.get_model("unterweisung", "MultipleChoiceFrage")

    # Copy all Fragen
    for seite in MultipleChoiceSeite.objects.all():
        for frage in seite.fragen.all():
            antworten = frage.antworten.all()

            frage.pk = None
            frage.seite = seite
            frage.save()

            for antwort in antworten:
                antwort.pk = None
                antwort.frage = frage
                antwort.save()

    # Now remove all old (with seite=None
    MultipleChoiceFrage.objects.filter(seite__isnull=True).delete()


def fill_old(apps, schema_editor):
    MultipleChoiceSeite = apps.get_model("unterweisung", "MultipleChoiceSeite")
    MultipleChoiceFrage = apps.get_model("unterweisung", "MultipleChoiceFrage")

    # fill MultipleChoiceSeite.fragen
    for seite in MultipleChoiceSeite.objects.all():
        seite.fragen.set(seite.fragen_neu.all())


class Migration(migrations.Migration):

    dependencies = [
        ('unterweisung', '0024_alter_fahrerlaubnis_fuehrerschein_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplechoicefrage',
            name='seite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fragen_neu', to='unterweisung.multiplechoiceseite'),
        ),
        migrations.RunPython(code=fill_new, reverse_code=fill_old),
        migrations.RemoveField(
            model_name='multiplechoiceseite',
            name='fragen',
        ),
        migrations.AlterField(
            model_name='multiplechoicefrage',
            name='seite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fragen', to='unterweisung.multiplechoiceseite'),
        ),
    ]
