# Generated by Django 5.2.7 on 2025-11-28 03:35

import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unterweisung', '0025_multiplechoicefrage_seite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoseite',
            name='content',
            field=markdownx.models.MarkdownxField(help_text='Inhalt der Folie als <a href="https://www.markdownguide.org/basic-syntax/" target="_blank">Markdown-Formatierung</a>: Absätze werden durch eine freie Zeile getrennt, Text kann <code><b>**fett**</b></code> und <code><i>*kursiv*</i></code> hervorgehoben werden. Bilder können außerhalb kopiert und im Textfeld eingefügt werden, sie erscheinen dann als <code>![](/media/....)</code>.', verbose_name='Inhalt'),
        ),
        migrations.AlterField(
            model_name='seite',
            name='is_required',
            field=models.BooleanField(default=True, help_text='Muss diese Seite erfolgreich abgeschlossen werden, um eine Teilnahme zu hinterlegen?', verbose_name='Erforderlich'),
        ),
        migrations.AlterField(
            model_name='seite',
            name='sort',
            field=models.IntegerField(db_index=True, default=0, help_text='Sortierreihenfolge der Seite innerhalb der Unterweisung', verbose_name='Reihenfolge'),
        ),
        migrations.AlterField(
            model_name='seite',
            name='titel',
            field=models.CharField(help_text='Überschrift der Seite', max_length=70, verbose_name='Titel'),
        ),
    ]
