# Generated by Django 5.1.5 on 2025-11-27 08:36

import django.db.models.deletion
from django.db import migrations, models


def fill_new(apps, schema_editor):
    MultipleChoiceSeite = apps.get_model("unterweisung", "MultipleChoiceSeite")
    MultipleChoiceFrage = apps.get_model("unterweisung", "MultipleChoiceFrage")

    # Copy all Fragen
    for seite in MultipleChoiceSeite.objects.all():
        for frage in seite.fragen.all():
            antworten = frage.antworten.all()

            frage.pk = None
            frage.seite = seite
            frage.save()

            for antwort in antworten:
                antwort.pk = None
                antwort.frage = frage
                antwort.save()

    # Now remove all old (with seite=None)
    MultipleChoiceFrage.objects.filter(seite__isnull=True).delete()


def fill_old(apps, schema_editor):
    MultipleChoiceSeite = apps.get_model("unterweisung", "MultipleChoiceSeite")
    MultipleChoiceFrage = apps.get_model("unterweisung", "MultipleChoiceFrage")

    # fill MultipleChoiceSeite.fragen
    for seite in MultipleChoiceSeite.objects.all():
        seite.fragen.set(seite.fragen_neu.all())


class Migration(migrations.Migration):

    dependencies = [
        ('unterweisung', '0025_multiplechoicefrage_seite_1'),
    ]

    operations = [
        migrations.RunPython(code=fill_new, reverse_code=fill_old),
    ]
