# Generated by Django 5.1.5 on 2025-11-27 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unterweisung', '0026_multiplechoicefrage_seite_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiplechoiceseite',
            name='fragen',
        ),
        migrations.AlterField(
            model_name='multiplechoicefrage',
            name='seite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fragen', to='unterweisung.multiplechoiceseite'),
        ),
    ]
