# Generated by Django 6.0 on 2026-02-13 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cacheitem',
            name='error_value',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='cacheitem',
            name='has_error',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cacheitem',
            name='value',
            field=models.JSONField(default=None, null=True),
        ),
    ]
