# Generated by Django 5.0.4 on 2024-05-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abfrage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='customer_uid',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='served_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='closed_at',
            field=models.DateTimeField(blank=True, help_text='Zeitpunkt bis zu dem Anmeldungen entgegen genommen werden. Kann leer gelassen werden, wenn die Anmeldung später von Hand geschlossen werden soll.', null=True, verbose_name='Anmeldeschluss'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='label',
            field=models.CharField(help_text='Eindeutiger Name des Essensmenüs, z.B. "Dienst 7. Mai 2024"', max_length=100, verbose_name='Bezeichnung'),
        ),
        migrations.AlterField(
            model_name='serving',
            name='icon',
            field=models.CharField(choices=[('beef', 'Rind'), ('pork', 'Schwein'), ('chicken', 'Hähnchen'), ('piscine', 'Fisch'), ('vegetarian', 'Vegetarisch'), ('vegan', 'Vegan')], max_length=20),
        ),
    ]
